### ISSUE TITLE
iOS 8.3 Crash in supportedInterfaceOrientations

### ISSUE THREAD

**Issue by kokhong20** [jaydee3/JDStatusBarNotification#42]
![screen shot 2015-04-20 at 6 46 04 pm](https://cloud.githubusercontent.com/assets/3205289/7228627/ac7e6dd4-e78d-11e4-8420-4f76b707ea00.png)

I am using iOS SDK 8.3 and running on devices with iOS 8.3 and it keep crashing whenever i want to dismiss a modal view when JDStatusBar is shown. 
Seems like Apple has changed the 
```
supportedInterfaceOrientations
```
implementation. Is there any work around i can solve this exception?

Thanks

**Comment by stasel** [comment]
I can confirm this happens to me as well. App crashes when I try to present UIAlertView while the status bar is shown.

**Comment by bartg** [comment]
Happens to me as well. Working on fix now, will keep you informed :)

**Comment by bartg** [comment]
I can confirm that using version pulled from top of master is NOT crashing,

    pod 'JDStatusBarNotification', :head

Phew, not lets hope for fast review.

**Comment by bartg** [comment]
Version 1.5.1 from Pods also works. So normal

   pod update

should be enough.

**Comment by manobal** [comment]
I do have 1.5.1 but I keep seeing crashes in supportedInterfaceOrientations

**Comment by kokhong20** [comment]
@bartg I have pulled the latest version from master and it solved the crash. Thanks! 
Btw, i am developing iPad applications and my device orientation is fixed to landscape only.

**Comment by bartg** [comment]
@kokhong20 Could you ack that it works for you also not on master but also on 1.5.1? I am also developing iPad app with fixed landscape orientation and it stopped crashing at 1.5.1.

I dont want to use :head for my pods, because every pod install it is being updated.

**Comment by jaydee3** [comment]
added 1.5.2 pod, hope that helps.

**Comment by kokhong20** [comment]
@bartg I have tried 1.5.1 and it works. I will close this issue.
