### ISSUE TITLE
about the overlaywindow

### ISSUE THREAD

**Issue by keyjacky** [jaydee3/JDStatusBarNotification#47]
i'm wonder the overlaywindow

what 's  it's superview?

i try to po it but it's null

is overlaywindow equal application.keywindow?

PS:

after i read the code

i just find you creat the overlaywindow

but i can't find where you display it

please help

**Comment by jaydee3** [comment]
If you set a window to hidden = NO, it is visible. It's not the key window. It's a seperate window. The windowLevel defines if it is on top of other windows or not.
