### ISSUE TITLE
AppStore approval does not pass

### ISSUE THREAD

**Issue by graceydb** [jaydee3/JDStatusBarNotification#49]

**Comment by jaydee3** [comment]
Can you post your rejection mail? thx. It depends on your usage, if it goes through or not, but apple definitely doesn't like covering the status bar, Thus I mentioned it in my readme, will add your task there.

**Comment by jaydee3** [comment]
Also see #15 and #30

**Comment by alimoeeny** [comment]
@graceydb can you please explain how you used this library that ended up in rejection? Or can you please  post a screenshot. Basically I want to know what counts as violation of the HIG. Thanks.
