### ISSUE TITLE
How can i give JDStatusBarView a click event.

### ISSUE THREAD

**Issue by LargeShrimp** [jaydee3/JDStatusBarNotification#71]
How can i give JDStatusBarView a click event. And I want to d processing some events. Thanks in advance!

**Comment by jaydee3** [comment]
Not possible currently, since it is a different window.

**Comment by jaydee3** [comment]
See #66 for a possible solution

**Comment by LargeShrimp** [comment]
@calimarkus  ok， That's good, Thank you vert much !
